server:
  port: 8080

spring:
  profiles:
    active: sqlite

  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8

# MyBatis 配置
mybatis:
  type-aliases-package: com.example.uav.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper 分页配置
pagehelper:
  helper-dialect: sqlite
  reasonable: true
  support-methods-arguments: true
